-- DEWECS UC-02 (relief logistics and post-event analytics): the NEW tables for the shared Neon database.
-- Run by hand in the Neon SQL editor, ONCE, BEFORE the new backend is deployed. Claude/automation never runs this file.
--
-- Why it must run first: the default profile starts with ddl-auto=validate, which refuses to start when an entity's
-- table is missing. The new code maps six tables that do not exist in Neon yet.
--
-- What it does: CREATE TABLE IF NOT EXISTS only. No existing table or column is changed (relief_consignments,
-- post_event_reports and report_metrics are untouched; the extra data lives in new tables that point at them).
-- Safe to run again. Tell the team before running it (Neon is shared); older code keeps working.
--
-- Column types follow what Hibernate expects (bigint identity ids, varchar enums, timestamp(6)).

BEGIN;

-- 1. What a shelter says it still needs ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shelter_needs (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_id         bigint       NOT NULL REFERENCES shelters (id),
    resource_type      varchar(255) NOT NULL CHECK (resource_type IN ('FOOD','WATER','MEDICAL_SUPPLIES','SHELTER_MATERIALS','EQUIPMENT','FUEL','OTHER')),
    quantity_needed    integer      NOT NULL,
    quantity_allocated integer      NOT NULL,
    urgent             boolean      NOT NULL,
    status             varchar(255) NOT NULL CHECK (status IN ('OPEN','MET','CANCELLED')),
    note               varchar(500),
    requested_at       timestamp(6) NOT NULL
);

-- 2. Dispatch details of a consignment (convoy, split link, handover) -----------------------------------------------
CREATE TABLE IF NOT EXISTS consignment_details (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consignment_id        bigint NOT NULL UNIQUE REFERENCES relief_consignments (id),
    hazard_event_id       bigint REFERENCES hazard_events (id),
    parent_consignment_id bigint REFERENCES relief_consignments (id),
    shelter_need_id       bigint REFERENCES shelter_needs (id),
    handling_notes        varchar(1000),
    vehicle               varchar(100),
    driver_name           varchar(255),
    driver_phone          varchar(50),
    expected_arrival      timestamp(6),
    received_by           varchar(255),
    received_quantity     integer,
    damaged_quantity      integer,
    handover_note         varchar(1000),
    handover_photo_url    varchar(255),
    handed_over_at        timestamp(6)
);

-- 3. Audit log of everything that happens to a consignment --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consignment_events (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consignment_id bigint       NOT NULL REFERENCES relief_consignments (id),
    event_type     varchar(255) NOT NULL CHECK (event_type IN ('DISPATCHED','FIELD_UNIT_NOTIFIED','REROUTED','DRIVER_NOTIFIED','HANDOVER','DAMAGE_REPORTED','CANCELLED')),
    detail         varchar(500),
    recorded_by    varchar(255),
    created_at     timestamp(6) NOT NULL
);

-- 4. What each responding agency was told -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agency_notifications (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint       NOT NULL REFERENCES organizations (id),
    consignment_id  bigint REFERENCES relief_consignments (id),
    message         varchar(500) NOT NULL,
    created_at      timestamp(6) NOT NULL
);

-- 5. Parameters, data-gap status and approval of a post-event report ---------------------------------------------------
CREATE TABLE IF NOT EXISTS report_details (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id             bigint  NOT NULL UNIQUE REFERENCES post_event_reports (id),
    window_from           timestamp(6),
    window_to             timestamp(6),
    donor_organization_id bigint REFERENCES organizations (id),
    provisional           boolean NOT NULL,
    provisional_reason    varchar(1000),
    data_gaps             varchar(1000),
    approved_by           varchar(255),
    approved_at           timestamp(6)
);

-- 6. Performance indicators of a report ---------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS report_kpis (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id  bigint       NOT NULL REFERENCES post_event_reports (id),
    kpi_key    varchar(50)  NOT NULL,
    label      varchar(150) NOT NULL,
    kpi_value  float(53),
    unit       varchar(40),
    detail     varchar(500),
    sort_order integer
);

COMMIT;
