-- DEWECS UC-01 (warnings): the NEW tables for the shared Neon database. Run by hand in the Neon SQL editor, ONCE,
-- BEFORE the new backend is deployed. Claude/automation never runs this file.
--
-- Why it must run first: the default profile starts with ddl-auto=validate, which refuses to start when an entity's
-- table is missing. The new code maps four tables that do not exist in Neon yet.
--
-- What it does: CREATE TABLE IF NOT EXISTS only. No existing table or column is changed (the warnings table is
-- untouched; the districts a warning covers live in the new join table warning_districts). Safe to run again.
-- Tell the team before running it (Neon is shared); older code that does not know these tables keeps working.
--
-- The column types follow what Hibernate expects (bigint ids, varchar(255) enums, timestamp(6)).

BEGIN;

-- 1. River basins and the districts they run through ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS river_basins (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS river_basin_districts (
    river_basin_id bigint NOT NULL REFERENCES river_basins (id),
    district_id    bigint NOT NULL REFERENCES districts (id),
    PRIMARY KEY (river_basin_id, district_id)
);

-- 2. The districts a warning covers (a river-basin warning covers several) -----------------------------------------
CREATE TABLE IF NOT EXISTS warning_districts (
    warning_id  bigint NOT NULL REFERENCES warnings (id),
    district_id bigint NOT NULL REFERENCES districts (id),
    PRIMARY KEY (warning_id, district_id)
);
CREATE INDEX IF NOT EXISTS idx_warning_districts_district ON warning_districts (district_id);

-- 3. The delivery log: one row per attempt to send a warning on a channel -----------------------------------------------
CREATE TABLE IF NOT EXISTS alert_delivery_logs (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warning_id   bigint       NOT NULL REFERENCES warnings (id),
    channel      varchar(255) NOT NULL
        CHECK (channel IN ('SMS', 'EMAIL', 'RADIO', 'TV', 'SIREN', 'APP_PUSH', 'SOCIAL_MEDIA')),
    attempt      integer      NOT NULL,
    outcome      varchar(255) NOT NULL CHECK (outcome IN ('SENT', 'FAILED')),
    trigger_type varchar(255) NOT NULL CHECK (trigger_type IN ('PUBLISH', 'ESCALATION', 'RETRY')),
    fallback_for varchar(255)
        CHECK (fallback_for IS NULL OR fallback_for IN ('SMS', 'EMAIL', 'RADIO', 'TV', 'SIREN', 'APP_PUSH', 'SOCIAL_MEDIA')),
    recipients   integer,
    detail       varchar(500),
    created_at   timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alert_delivery_logs_warning ON alert_delivery_logs (warning_id);

-- 4. Seed the river basins (skipped for any district that does not exist, and when a basin already exists) ----------------
INSERT INTO river_basins (name)
SELECT v.name
FROM (VALUES ('Kelani Ganga'), ('Kalu Ganga'), ('Gin Ganga'), ('Nilwala Ganga'), ('Mahaweli Ganga')) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM river_basins b WHERE b.name = v.name);

INSERT INTO river_basin_districts (river_basin_id, district_id)
SELECT b.id, d.id
FROM (VALUES
    ('Kelani Ganga',   'Colombo'),
    ('Kelani Ganga',   'Gampaha'),
    ('Kalu Ganga',     'Kalutara'),
    ('Kalu Ganga',     'Ratnapura'),
    ('Gin Ganga',      'Galle'),
    ('Nilwala Ganga',  'Matara'),
    ('Mahaweli Ganga', 'Kandy'),
    ('Mahaweli Ganga', 'Badulla')
) AS v(basin, district)
JOIN river_basins b ON b.name = v.basin
JOIN districts d ON d.name = v.district
WHERE NOT EXISTS (SELECT 1 FROM river_basin_districts x WHERE x.river_basin_id = b.id AND x.district_id = d.id);

COMMIT;

-- Check (read-only): the tables exist and the basins are linked.
SELECT to_regclass('public.river_basins')          AS river_basins,
       to_regclass('public.river_basin_districts') AS river_basin_districts,
       to_regclass('public.warning_districts')     AS warning_districts,
       to_regclass('public.alert_delivery_logs')   AS alert_delivery_logs;

SELECT b.name AS basin, string_agg(d.name, ', ' ORDER BY d.name) AS districts
FROM river_basins b
LEFT JOIN river_basin_districts x ON x.river_basin_id = b.id
LEFT JOIN districts d ON d.id = x.district_id
GROUP BY b.name
ORDER BY b.name;
