-- DEWECS UC-03 (coordinate shelter and rescue operations): the NEW tables for the shared Neon database.
-- Run by hand in the Neon SQL editor, ONCE, BEFORE the new backend is deployed. Claude/automation never runs this file.
--
-- Why it must run first: the default profile starts with ddl-auto=validate, which refuses to start when an entity's
-- table is missing. The new code maps two tables that do not exist in Neon yet.
--
-- What it does: CREATE TABLE IF NOT EXISTS only. No existing table or column is changed (rescue_teams, shelters and
-- rescue_requests are untouched; the extra team data lives in rescue_team_profiles). Safe to run again.
-- Tell the team before running it (Neon is shared); older code keeps working.

BEGIN;

-- 1. Capability, base position and field progress of a rescue team ------------------------------------------------------
CREATE TABLE IF NOT EXISTS rescue_team_profiles (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id           bigint       NOT NULL UNIQUE REFERENCES rescue_teams (id),
    capability        varchar(255) NOT NULL CHECK (capability IN ('GENERAL','WATER_RESCUE','MEDICAL','SEARCH','FIRE')),
    base_lat          numeric(9,6),
    base_lng          numeric(9,6),
    stage             varchar(255) CHECK (stage IN ('EN_ROUTE','ON_SITE','TASK_COMPLETE')),
    status_updated_at timestamp(6),
    support_note      varchar(500)
);

-- 2. The district coordination audit trail --------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS coordination_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id     bigint REFERENCES districts (id),
    event_type      varchar(255) NOT NULL CHECK (event_type IN ('OCCUPANCY_UPDATED','SHELTER_FLAGGED','TEAM_DISPATCHED','CROSS_ORG_CONFIRMED','TEAM_STATUS','SUPPORT_REQUESTED','UNASSIGNED_ESCALATED','SUPPLY_LOGGED','SYNC_CONFLICT','EMPTY_DISTRICT')),
    subject         varchar(255),
    detail          varchar(500),
    recorded_by     varchar(255),
    organization_id bigint REFERENCES organizations (id),
    client_time     timestamp(6),
    needs_review    boolean      NOT NULL,
    created_at      timestamp(6) NOT NULL
);

COMMIT;
