-- DEWECS UC-01 map location: ONE new table for the shared Neon database (owner-approved new-table exception).
-- Run by hand in the Neon SQL editor, ONCE, BEFORE the new backend is deployed (ddl-auto=validate). Never run by automation.
-- CREATE TABLE IF NOT EXISTS only; hazard_events is untouched. Safe to run again.

BEGIN;

CREATE TABLE IF NOT EXISTS hazard_event_locations (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hazard_event_id bigint        NOT NULL UNIQUE REFERENCES hazard_events (id),
    lat             numeric(9,6)  NOT NULL,
    lng             numeric(9,6)  NOT NULL
);

COMMIT;
