spring:
  application:
    name: dewecs

  datasource:
    url: postgresql://ep-shy-firefly-b4tftv64-pooler.c-6.us-east-2.aws.neon.tech/prod?sslmode=require
    username: neondb_owner
    password: npg_S7ihUD4brJYK
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
